# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - feature/sso-implementation

pool:
  vmImage: windows-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: "Project-da08-d-904380-ServiceEndPoint"
      scriptType: "ps"
      scriptLocation: "inlineScript"
      inlineScript: "az webapp config appsettings set --resource-group bieno-da08-d-904380-rg --name bieno-da08-d-904380-webapi-02 --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "Project-da08-d-904380-ServiceEndPoint"
      scriptType: "ps"
      scriptLocation: "inlineScript"
      inlineScript: 'az webapp up --resource-group bieno-da08-d-904380-rg --name bieno-da08-d-904380-webapi-02 --os-type Windows --runtime "NODE:18LTS" --plan "bieno-da08-d-904380-serviceplan-02"'

  - task: AzureCLI@2
    inputs:
      azureSubscription: "Project-da08-d-904380-ServiceEndPoint"
      scriptType: "ps"
      scriptLocation: "inlineScript"
      inlineScript: 'az keyvault key list --vault-name bnlwe-da02-b-902592-kv01'
