# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  - uat

pool:
  vmImage: windows-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: "Project-da06-u-904378-ServiceEndPoint"
      scriptType: "ps"
      scriptLocation: "inlineScript"
      inlineScript: "az webapp config appsettings set --resource-group bieno-da06-u-904378-rg --name bieno-da06-u-904378-webapi-02 --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "Project-da06-u-904378-ServiceEndPoint"
      scriptType: "ps"
      scriptLocation: "inlineScript"
      inlineScript: 'az webapp up --resource-group bieno-da06-u-904378-rg --name bieno-da06-u-904378-webapi-02 --os-type Windows --runtime "NODE:18LTS" --plan "bieno-da06-u-904378-serviceplan-02"'

