module.exports = [
  { header: "File Name", key: "Filename", width: 60 },
  { header: "Tag", key: "Tag", width: 30 },
  {
    header: "Category",
    key: "Category",
    width: 30,
  },
  {
    header: "Country",
    key: "Country",
    width: 30,
  },
  { header: "Long", key: "Long", width: 30 },
  { header: "Periodicity", key: "Periodicity", width: 30 },
  { header: "Periodicity Identifer", key: "PeriodicityIdentifer", width: 30 },
  { header: "Last Period Tag Format", key: "LastPeriodTagFormat", width: 30 },
  { header: "Convention", key: "Convention", width: 30 },
  { header: "YearBr", key: "YearBr", width: 30 },
  { header: "WeekBr", key: "WeekBr", width: 30 },
  { header: "QuarterBr", key: "QuarterBr", width: 30 },
  { header: "MonthBr", key: "MonthBr", width: 30 },
  { header: "MonthNumber", key: "MonthNumber", width: 30 },
  { header: "PeriodNumberBr", key: "PeriodNumberBr", width: 30 },
  { header: "MinPeriodNumBr", key: "MinPeriodNumBr", width: 30 },
  { header: "MaxPeriodNumBr", key: "MaxPeriodNumBr", width: 30 },
  { header: "YearWeek", key: "YearWeek", width: 30 },
  { header: "YearMonth", key: "YearMonth", width: 30 },
  { header: "WeekStartDayCountry", key: "WeekStartDayCountry", width: 30 },
  { header: "PeriodStartDate", key: "PeriodStartDate", width: 30 },
  { header: "PeriodEndDate", key: "PeriodEndDate", width: 30 },
  {
    header: "Unique TAG",
    key: "UniqueTag",
    width: 30,
  },
  { header: "CellPeriod", key: "CellPeriod", width: 30 },
  {
    header: "Created On",
    key: "Createdon",
    width: 30,
  },
  {
    header: "Flag",
    key: "Flag",
    width: 30,
  },
  {
    header: "Confidence Score",
    key: "ConfidenceScore",
    width: 30,
  },
  {
    header: "Confidence Level",
    key: "ConfidenceLevel",
    width: 30,
  },
  {
    header: "ISOCountry",
    key: "ISOCountry",
    width: 30,
  },
];
