const { DataTypes } = require("sequelize");
const sequelize = require("../../config/sequelize.config");

const ProductOtherRMSModel = sequelize.define(
  "MappingProductOutput_RMS",
  {
    Id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    Tag: DataTypes.STRING,
    Filename: DataTypes.STRING,
    Internaldesc: DataTypes.STRING,
    Externaldesc: DataTypes.STRING,
    Skucode: DataTypes.STRING,
    Hierlevelname: DataTypes.STRING,
    Categoryname: DataTypes.STRING,
    Divisionname: DataTypes.STRING,
    Categorygroupname: DataTypes.STRING,
    Segmentname: DataTypes.STRING,
    Productformmediumname: DataTypes.STRING,
    Confidencelevel: DataTypes.STRING,
    Brandformname: DataTypes.STRING,
    Confidencescore: DataTypes.STRING,
    Spfvname: DataTypes.STRING,
    Categoryname: DataTypes.STRING,
    Marketname: DataTypes.STRING,
    Corporatebrandname: DataTypes.STRING,
    Productformname: DataTypes.STRING,
    Sectorname: DataTypes.STRING,
    Formname: DataTypes.STRING,
    Subformname: DataTypes.STRING,
    Productpackformname: DataTypes.STRING,
    Productpacksizename: DataTypes.STRING,
    Productvariantname: DataTypes.STRING,
    Productcodename: DataTypes.STRING,
    Subformname: DataTypes.STRING,
    Short: DataTypes.STRING,
    Hiernum: DataTypes.STRING,
    Hiername: DataTypes.STRING,
    Hierlevelnum: DataTypes.STRING,
    Parenttag: DataTypes.STRING,
    Company: DataTypes.STRING,
    Brand: DataTypes.STRING,
    Productname: DataTypes.STRING,
    Flag: DataTypes.STRING,
    Scenarioflag: DataTypes.STRING,
    Maxattrilifestage: DataTypes.STRING,
    Maxattrigender: DataTypes.STRING,
    Maxattrilaundryvariants: DataTypes.STRING,
    Maxattripacktype: DataTypes.STRING,
    Maxattriformat: DataTypes.STRING,
    Maxattrifatcontent: DataTypes.STRING,
    Maxattribenefitclaim: DataTypes.STRING,
    Maxattritargetuse: DataTypes.STRING,
    Maxattriformation: DataTypes.STRING,
    Maxattriifantiperspirant: DataTypes.STRING,
    Maxattriifconcentrate: DataTypes.STRING,
    Maxattriifrinseoff: DataTypes.STRING,
    Maxattriifhighsuds: DataTypes.STRING,
  },
  {
    tableName: "MappingProductOutput_RMS",
    schema: "Mapping",
    timestamps: false,
  }
);

module.exports = ProductOtherRMSModel;
