const { DataTypes } = require("sequelize");
const sequelize = require("../config/sequelize.config");

const SmlPcatModel = sequelize.define(
  "settings_sml_pcat",
  {
    Version: DataTypes.STRING,
    "category id": DataTypes.STRING,
    category: DataTypes.STRING,
    created: DataTypes.STRING,
    GTC_ITEM_PCAT_ID: { type: DataTypes.STRING, primaryKey: true },
    DP_TOTAL: DataTypes.STRING,
    DP_CATEGORY_GRP: DataTypes.STRING,
    DP_CATEGORY: DataTypes.STRING,
    DP_MARKET: DataTypes.STRING,
    DP_SEGMENT: DataTypes.STRING,
    DP_SUBSEGMENT: DataTypes.STRING,
    DP_TYPE: DataTypes.STRING,
    DP_FORMAT: DataTypes.STRING,
    DP_FORM: DataTypes.STRING,
    DP_CORE_BENEFIT: DataTypes.STRING,
    DP_TARGET_AREA: DataTypes.STRING,
    DP_TARGET_USER: DataTypes.STRING,
    DP_PACK_TYPE: DataTypes.STRING,
    DP_PLATFORM: DataTypes.STRING,
    DP_MACHINE_VS_HAND: DataTypes.STRING,
    DP_SUBFORMAT: DataTypes.STRING,
    MONITOR_REASON: DataTypes.STRING,
    MONITOR_REASON_LD: DataTypes.STRING,
    HIDDEN_YN: DataTypes.STRING,
    "map updated": DataTypes.STRING,
    PCat_Id: DataTypes.STRING,
    "MIP_PCAT_NAME(Product Form)": DataTypes.STRING,
    MIP_ITEM_ATTRS_ID: DataTypes.STRING,
    AG004: DataTypes.STRING,
    FORMAT: DataTypes.STRING,
    AG011: DataTypes.STRING,
    IF_RINSE_OFF: DataTypes.STRING,
    AG003: DataTypes.STRING,
    PACK_TYPE: DataTypes.STRING,
    AG006: DataTypes.STRING,
    BENEFIT_CLAIM: DataTypes.STRING,
    AG007: DataTypes.STRING,
    TARGET_USE: DataTypes.STRING,
    AG002: DataTypes.STRING,
    LAUNDRY_VARIANTS: DataTypes.STRING,
    AG010: DataTypes.STRING,
    IF_CONCENTRATE: DataTypes.STRING,
    AG001: DataTypes.STRING,
    GENDER: DataTypes.STRING,
    AG012: DataTypes.STRING,
    IF_HIGH_SUDS: DataTypes.STRING,
    AG009: DataTypes.STRING,
    IF_ANTIPERSPIRANT: DataTypes.STRING,
    AG008: DataTypes.STRING,
    FORMATION: DataTypes.STRING,
    AG013: DataTypes.STRING,
    LIFESTAGE: DataTypes.STRING,
    AG005: DataTypes.STRING,
    FAT_CONTENT: DataTypes.STRING,
  },
  {
    tableName: "settings_sml_pcat",
    schema: "metadata",
    timestamps: false,
  }
);

module.exports = SmlPcatModel;
