const { DataTypes } = require("sequelize");
const sequelize = require("../config/sequelize.config");

const SmlPcatModel = sequelize.define(
  "settings_sml_pcat",
  {
    SML_ID: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    category_id: DataTypes.STRING,
    category: DataTypes.STRING,
    created: DataTypes.STRING,
    GTC_ITEM_PCAT_ID: DataTypes.NUMBER,
    DP_TOTAL: DataTypes.STRING,
    DP_CATEGORY_GRP: DataTypes.STRING,
    DP_CATEGORY: DataTypes.STRING,
    DP_MARKET: DataTypes.STRING,
    DP_SEGMENT: DataTypes.STRING,
    DP_SUBSEGMENT: DataTypes.STRING,
    DP_TYPE: DataTypes.STRING,
    DP_FORMAT: DataTypes.STRING,
    DP_FORM: DataTypes.STRING,
    DP_CORE_BENEFIT: DataTypes.STRING,
    DP_TARGET_AREA: DataTypes.STRING,
    DP_TARGET_USER: DataTypes.STRING,
    DP_PACK_TYPE: DataTypes.STRING,
    DP_PLATFORM: DataTypes.STRING,
    DP_MACHINE_VS_HAND: DataTypes.STRING,
    DP_SUBFORMAT: DataTypes.STRING,
    MONITOR_REASON: DataTypes.STRING,
    MONITOR_REASON_LD: DataTypes.STRING,
    HIDDEN_YN: DataTypes.STRING,
    map_updated: DataTypes.STRING,
    PCat_Id: DataTypes.STRING,
    MIP_PCAT_NAME: DataTypes.STRING,
    MIP_ITEM_ATTRS_ID: DataTypes.NUMBER,
    AG004: DataTypes.STRING,
    Maxattriformat: DataTypes.STRING,
    AG011: DataTypes.STRING,
    Maxattriifrinseoff: DataTypes.STRING,
    AG003: DataTypes.STRING,
    Maxattripacktype: DataTypes.STRING,
    AG006: DataTypes.STRING,
    Maxattribenefitclaim: DataTypes.STRING,
    AG007: DataTypes.STRING,
    Maxattritargetuse: DataTypes.STRING,
    AG002: DataTypes.STRING,
    Maxattrilaundryvariants: DataTypes.STRING,
    AG010: DataTypes.STRING,
    Maxattriifconcentrate: DataTypes.STRING,
    AG001: DataTypes.STRING,
    Maxattrigender: DataTypes.STRING,
    AG012: DataTypes.STRING,
    Maxattriifhighsuds: DataTypes.STRING,
    AG009: DataTypes.STRING,
    Maxattriifantiperspirant: DataTypes.STRING,
    AG008: DataTypes.STRING,
    Maxattriformation: DataTypes.STRING,
    AG013: DataTypes.STRING,
    Maxattrilifestage: DataTypes.STRING,
    AG005: DataTypes.STRING,
    Maxattrifatcontent: DataTypes.STRING
  },
  {
    tableName: "settings_sml_pcat",
    schema: "metadata",
    timestamps: false,
  }, {
    constraints: false
  }
);

module.exports = SmlPcatModel;
